print("{:<50}".format('Twinkle, twinkle, little star,'))
print("{:^50}".format('How I wonder what you are! '))
print("{:>50}".format('Up above the world so high,'))
print("{:>50}".format('Like a diamond in the sky.'))
print("{:<50}".format('Twinkle, twinkle, little star,'))
print("{:^50}".format('Twinkle, twinkle, little star,'))